import Head from "next/head";

export default function Home() {
  // console.log(movies);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>hello</h3>
      <div>
        <h3>Hello</h3>
      </div>
    </div>
  );
}
